//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallManagerSpace.Raws {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmallManagerSpace.Raws.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xdo=&quot;urn:pxp&quot; xmlns:ms=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:stack=&quot;urn:anything&quot; xmlns:xdb=&quot;http://xmlns.oracle.com/xdb&quot; xmlns:w=&quot;http://www.fiberhome.com.cn/board/control&quot;&gt;  
        ///  &lt;xsd:simpleType name=&quot;TIME4BYTE&quot;&gt;
        ///    &lt;xsd:restriction base=&quot;xsd:hexBinary&quot;&gt;
        ///      &lt;xsd:length value=&quot;4&quot;/&gt;
        ///    &lt;/xsd:restriction&gt;
        ///  &lt;/xsd:simpleType&gt;
        ///  &lt;xsd:simpleType name=&quot;configBlockName&quot;&gt;
        ///    &lt;xsd:restriction base=&quot;xsd [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Base_Enum {
            get {
                return ResourceManager.GetString("Base_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon BlockIco {
            get {
                object obj = ResourceManager.GetObject("BlockIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///
        ///&lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xdo=&quot;urn:pxp&quot; xmlns:ms=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:stack=&quot;urn:anything&quot; xmlns:xdb=&quot;http://xmlns.oracle.com/xdb&quot; xmlns:w=&quot;http://www.fiberhome.com.cn/board/control&quot;&gt;  
        ///  &lt;!--***********************简单类型***********************--&gt;
        ///  &lt;xsd:simpleType name=&quot;IMA_Clock_Mode&quot;&gt;
        ///    &lt;xsd:restriction base=&quot;xsd:byte&quot;&gt;
        ///      &lt;xsd:length value=&quot;1&quot;/&gt;
        ///      &lt;xsd:enumeration w:en=&quot;Sys_Clock&quot; w:cn=&quot;系统时钟&quot; value=&quot;00 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Enum {
            get {
                return ResourceManager.GetString("Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Green {
            get {
                object obj = ResourceManager.GetObject("Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon ParameterIco {
            get {
                object obj = ResourceManager.GetObject("ParameterIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon PathIco {
            get {
                object obj = ResourceManager.GetObject("PathIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Red {
            get {
                object obj = ResourceManager.GetObject("Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot;    xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;  xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xsl:output method =&quot;xml&quot; version =&quot;1.0&quot; encoding =&quot;gb2312&quot; indent=&quot;yes&quot; /&gt;
        ///  &lt;xsl:param name=&quot;baseFile&quot;/&gt;
        ///
        ///  &lt;xsl:template name=&quot;start&quot; match=&quot;node()&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:copy-of select=&quot;@*&quot; /&gt;
        ///      &lt;xsl:attribute name=&quot;CID&quot;&gt;
        ///        &lt;xsl:value-of select=&quot;generate-id(.)&quot;/&gt;
        ///      &lt;/xsl:attribute&gt;
        ///      &lt;xsl:apply-template [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Tamplate_XSL {
            get {
                return ResourceManager.GetString("Tamplate_XSL", resourceCulture);
            }
        }
    }
}
